### ISSUE TITLE
Makefile errors

### ISSUE THREAD

**Issue by connor557** [hackndev/linux-hnd#1]
Something is screwy with the Makefile. I'm trying to build a fork of the hackndev distro and the kernel just will not build. Will somebody please tell me what I'm doing wrong?

Console build log is as follows:

root@services:~/linux-hnd# make all ARCH=arm/mach-pxa/palmz72                   make: arm-linux-gcc: Command not found
Makefile:1441: *** mixed implicit and normal rules: deprecated syntax
/root/linux-hnd/Makefile:415: *** mixed implicit and normal rules: deprecated syntax
/root/linux-hnd/Makefile:1441: *** mixed implicit and normal rules: deprecated syntax
make[1]: *** No rule to make target 'silentoldconfig'.  Stop.
make: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.
root@services:~/linux-hnd# make ARCH=arm/mach-pxa/palmz72
make: arm-linux-gcc: Command not found
Makefile:1441: *** mixed implicit and normal rules: deprecated syntax
/root/linux-hnd/Makefile:415: *** mixed implicit and normal rules: deprecated syntax
/root/linux-hnd/Makefile:1441: *** mixed implicit and normal rules: deprecated syntax
make[1]: *** No rule to make target 'silentoldconfig'.  Stop.
make: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.
root@services:~/linux-hnd# make defconf ARCH=arm/mach-pxa/palmz72
make: arm-linux-gcc: Command not found
Makefile:1441: *** mixed implicit and normal rules: deprecated syntax
/root/linux-hnd/Makefile:415: *** mixed implicit and normal rules: deprecated syntax
/root/linux-hnd/Makefile:1441: *** mixed implicit and normal rules: deprecated syntax
make[1]: *** No rule to make target 'silentoldconfig'.  Stop.
make: *** No rule to make target 'defconf'.  Stop.

Any help is much appreciated, thanks much.

**Comment by sleep-walker** [comment]
Try to obtain cross compiler and feed [CROSS_COMPILE variable](https://github.com/hackndev/linux-hnd/blob/master/Makefile#L166). Makefile is standard.

If you want to build distro, explore it by yourself, there will be bigger challenges than the one you met (and you've got the answer in the log already).

**Comment by connor557** [comment]
By the way, are you (@Sleepwalker) the current maintainer of the hackndev l4p distribution? I'm really seeking guidance of any kind in building my own PDA linux distro. Any help is much appreciated.

Connor O.
Maintainer, Galaxy System Distribution

**Comment by sleep-walker** [comment]
The project is abandoned by all its developers for years. This is backup of our work.

If you are looking for some modern PDA distribution, check https://github.com/merproject instead.

**Comment by connor557** [comment]
Sorry, mer is not for ipaq/palm devices. However, I am starting a new project using bitbake and opie called the Galaxy System Distribution. Anyone interested can check out @galaxysys. 

I really hope some people can help me get going with my new project. Maybe you can help, or at least point me in the right direction?

Connor O.
Maintainer, @galaxysys

P.S. I will give mer another look too.
